apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: safegate
  labels:
    app: clamav
spec:
  type: ClusterIP
  selector:
    app: clamav
  ports:
    - name: clamav
      port: 3310
      targetPort: 3310
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: safegate
  labels:
    app: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
        - name: clamav
          image: clamav/clamav:stable
          ports:
            - containerPort: 3310
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
          readinessProbe:
            tcpSocket:
              port: 3310
            initialDelaySeconds: 120
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 3310
            initialDelaySeconds: 120
            periodSeconds: 60
          volumeMounts:
            - name: clamav-data
              mountPath: /var/lib/clamav
      volumes:
        - name: clamav-data
          emptyDir: {}
